---
- hosts: all
  sudo: true

  vars:
    CacheDir: /vagrant/apt-cacher-ng/cache
    LogDir: /vagrant/apt-cacher-ng/log

  pre_tasks:
    - name: update source to local mirror
      replace: dest=/etc/apt/sources.list 
         regexp='http://http.debian.net/debian'
         replace='http://kambing.ui.ac.id/debian'

         #replace='http://buaya.klas.or.id/debian'
    - name: update apt cache
      apt: update_cache=yes

    - name: Print interface
      debug:
        msg: "{{ item }}"
      with_items: ansible_interfaces

    - name: Print ipv4 
      debug:
        msg: "{{ item }}"
      with_items: ansible_all_ipv4_addresses

  roles:
    - install-docker
#    - apt-cacher-ng  # plain apt-cacher-ng 
    - docker-apt-cacher-ng

  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: install vim
      apt: name=vim state=present

    - name: install htop
      apt: name=htop state=present
