---

#- name: Add Apt Repository for Docker 
#  lineinfile: dest=/etc/apt/sources.list.d/docker.list state=present create=yes
#       line='deb http://apt.dockerproject.org/repo debian-jessie main'

#- name: Make sure apt can use https
#  apt: "name={{ item }} state=present"
#  with_items:
#    - apt-transport-https
#    - ca-certificates

- name: ensure `apt-transport-https` installed
  apt:
    name: apt-transport-https
    state: present

- name: add the Docker repository key to keychain
  #apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present
  apt_key: 
    keyserver: hkp://pgp.mit.edu:80 
    #keyserver: hkp://p80.pool.sks-keyservers.net:80 
    id: 58118E89F3A912897C070ADBF76221572C52609D 
    state: present

- name: Add Apt Repository for Docker
  apt_repository: 
    repo: 'deb http://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: install docker-engine
  apt: name=docker-engine state=present

- name: Start Docker service
  service: name=docker state=started

- name: add vagrant to docker group
  user: "name={{ ansible_ssh_user }} groups=docker append=yes"

- name: Get Install pip
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/vagrant/get-pip.py

- name: Install pip
  shell: python /vagrant/get-pip.py

- name: delete get-pip.py
  file: path=/vagrant/get-pip.py state=absent

- name: install docker-py
  pip:
    name: docker-py
    version: 1.1.0
    state: present
